[build-system]
requires = ["setuptools>=46.4.0", "wheel"]
build-backend = "setuptools.build_meta"
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
[tool.poetry.dependencies]
python = "^3.9"
