name: Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build --user
          pip install setuptools wheel twine
      - name: Build
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          
        #env:
        #  TWINE_USERNAME: __token__
        #  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        #run: |
          #python setup.py sdist bdist_wheel   https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
        #  twine upload --repository pypi dist/*
