name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pypa/build
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade build --user
          python3 -m build
          pip install setuptools wheel twine
      #- name: Build and publish
      #  env:
      #    TWINE_USERNAME: __token__
      #    TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      #  run: |
      #    python setup.py sdist bdist_wheel
      #    twine upload dist/*
      
      #- name: Build a binary wheel and a source tarball
      #  run: python3 -m build
      #- name: Store the distribution packages
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: python-package-distributions
      #    path: dist/
      # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
      # Run tox using the version of Python in `PATH`
        run: |
          curl https://raw.githubusercontent.com/ava007/a9x-webstatistics/main/tests/test_access_month01.log -o nginx_access.log
          ls -latr
          tox -e py
        # .github/workflows/ci-cd.yml

        
  #pypi-publish:
  #  name: Upload release to PyPI
  #  runs-on: ubuntu-latest
  #  environment:
  #    name: pypi
  #    url: https://pypi.org/p/a9x-webstatistics
  #  permissions:
  #    id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
  #  steps:
    # retrieve your distributions here

#    - name: Publish package distributions to PyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
